<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="118160" started-at="2018-07-02T03:37:07Z" finished-at="2018-07-02T03:39:05Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="118160" started-at="2018-07-02T03:37:07Z" finished-at="2018-07-02T03:39:05Z">
      <class name="com.learneAutomation.selenium.Login">
        <test-method status="PASS" signature="StartBrowser()[pri:0, instance:com.learneAutomation.selenium.Login@70d194]" name="StartBrowser" is-config="true" duration-ms="34693" started-at="2018-07-02T03:37:07Z" finished-at="2018-07-02T03:37:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- StartBrowser -->
        <test-method status="PASS" signature="Report()[pri:0, instance:com.learneAutomation.selenium.Login@70d194]" name="Report" is-config="true" duration-ms="679" started-at="2018-07-02T03:37:41Z" finished-at="2018-07-02T03:37:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Report -->
        <test-method status="PASS" signature="CloseWindowsAndPoups()[pri:1, instance:com.learneAutomation.selenium.Login@70d194]" name="CloseWindowsAndPoups" duration-ms="9384" started-at="2018-07-02T03:37:42Z" finished-at="2018-07-02T03:37:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseWindowsAndPoups -->
        <test-method status="PASS" signature="ScreenshotForFailure(org.testng.ITestResult)[pri:0, instance:com.learneAutomation.selenium.Login@70d194]" name="ScreenshotForFailure" is-config="true" duration-ms="3" started-at="2018-07-02T03:37:52Z" finished-at="2018-07-02T03:37:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=CloseWindowsAndPoups status=SUCCESS method=Login.CloseWindowsAndPoups()[pri:1, instance:com.learneAutomation.selenium.Login@70d194] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ScreenshotForFailure -->
        <test-method status="PASS" signature="Report()[pri:0, instance:com.learneAutomation.selenium.Login@70d194]" name="Report" is-config="true" duration-ms="82" started-at="2018-07-02T03:37:52Z" finished-at="2018-07-02T03:37:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Report -->
        <test-method status="FAIL" signature="LogInApplication()[pri:2, instance:com.learneAutomation.selenium.Login@70d194]" name="LogInApplication" duration-ms="48836" started-at="2018-07-02T03:37:52Z" finished-at="2018-07-02T03:38:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Search Jobs12] but found [Search Jobs]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Search Jobs12] but found [Search Jobs]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.learneAutomation.selenium.Login.LogInApplication(Login.java:86)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogInApplication -->
        <test-method status="FAIL" signature="ScreenshotForFailure(org.testng.ITestResult)[pri:0, instance:com.learneAutomation.selenium.Login@70d194]" name="ScreenshotForFailure" is-config="true" duration-ms="24415" started-at="2018-07-02T03:38:40Z" finished-at="2018-07-02T03:39:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LogInApplication status=FAILURE method=Login.LogInApplication()[pri:2, instance:com.learneAutomation.selenium.Login@70d194] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.learneAutomation.selenium.Login.ScreenshotForFailure(Login.java:154)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ScreenshotForFailure -->
        <test-method status="SKIP" signature="Report()[pri:0, instance:com.learneAutomation.selenium.Login@70d194]" name="Report" is-config="true" duration-ms="0" started-at="2018-07-02T03:39:05Z" finished-at="2018-07-02T03:39:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Report -->
        <test-method status="SKIP" signature="updateProfile()[pri:3, instance:com.learneAutomation.selenium.Login@70d194]" name="updateProfile" duration-ms="0" started-at="2018-07-02T03:39:05Z" finished-at="2018-07-02T03:39:05Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.learneAutomation.selenium.Login.ScreenshotForFailure(Login.java:154)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateProfile -->
        <test-method status="SKIP" signature="ScreenshotForFailure(org.testng.ITestResult)[pri:0, instance:com.learneAutomation.selenium.Login@70d194]" name="ScreenshotForFailure" is-config="true" duration-ms="0" started-at="2018-07-02T03:39:05Z" finished-at="2018-07-02T03:39:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ScreenshotForFailure -->
        <test-method status="SKIP" signature="Report()[pri:0, instance:com.learneAutomation.selenium.Login@70d194]" name="Report" is-config="true" duration-ms="0" started-at="2018-07-02T03:39:05Z" finished-at="2018-07-02T03:39:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Report -->
        <test-method status="SKIP" signature="LogOutApplication()[pri:4, instance:com.learneAutomation.selenium.Login@70d194]" name="LogOutApplication" duration-ms="0" started-at="2018-07-02T03:39:05Z" finished-at="2018-07-02T03:39:05Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.learneAutomation.selenium.Login.ScreenshotForFailure(Login.java:154)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogOutApplication -->
        <test-method status="SKIP" signature="ScreenshotForFailure(org.testng.ITestResult)[pri:0, instance:com.learneAutomation.selenium.Login@70d194]" name="ScreenshotForFailure" is-config="true" duration-ms="0" started-at="2018-07-02T03:39:05Z" finished-at="2018-07-02T03:39:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ScreenshotForFailure -->
        <test-method status="SKIP" signature="CloseDriver()[pri:0, instance:com.learneAutomation.selenium.Login@70d194]" name="CloseDriver" is-config="true" duration-ms="0" started-at="2018-07-02T03:39:05Z" finished-at="2018-07-02T03:39:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseDriver -->
      </class> <!-- com.learneAutomation.selenium.Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
